-- Seed idempotente: FAQs da Ouvidoria SAP/SP para todos os bots ativos
-- Fonte: https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html
SET search_path TO app;

WITH source_faq (ordem, pergunta, resposta, palavras_chave, fonte_externa) AS (
    VALUES
        (1, 'Como faço para obter informações de uma pessoa que acabou de ser presa.', 'Primeiro é importante saber qual a unidade prisional a pessoa está detida. Lembrando que a SAP e a Ouvidoria só atuam em situações que envolvam unidades prisionais (Centro de Detenção Provisória, Penitenciária, Semiaberto) no caso de Delegacia de Polícia deve-se procurar a Secretaria de Segurança Pública e sua Ouvidoria. (http://www.ssp.sp.gov.br/ouvidoria/)
Se você sabe onde a pessoa está detida entre em contato por telefone e procure o serviço social da unidade para maiores informações.', 'Como faço para obter informações de uma pessoa que acabou de ser presa.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (2, 'Não sei qual unidade meu familiar está detido.', 'O Paradeiro de Custodiados é o sistema utilizado por todos para localizar uma pessoa custodiada em Unidades Prisionais da Secretaria da Administração Penitenciária do Estado de São Paulo, disponível em: https://portal.sap.sp.gov.br/formularios/paradeiro
Para saber em qual Unidade Prisional está a pessoa custodiada, será necessário fornecer algumas informações.
O solicitante poderá fazer a pesquisa por Matrícula ou por CPF ou por RG ou por Nome + Nome da mãe + Data de nascimento. Além disso, o/a solicitante deve ter uma conta no Gov.br.
A conta Gov.br é uma identificação digital gratuita que permite aos cidadãos brasileiros acessar serviços públicos digitais com segurança. Caso ainda não tenha cadastro no Gov.br, clique aqui para ser direcionado para a página de cadastro.
A cada nova consulta, será necessário realizar um novo login no Gov.br', 'Não sei qual unidade meu familiar está detido.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (3, 'Posso ligar na unidade prisional para saber se meu familiar está bem?', 'Orientamos aos familiares que apenas informações essenciais e urgentes devem ser requeridas ou transmitidas via telefone, por exemplo, o preso possui doença e necessita de medicação específica, o preso possui problemas de convívio naquele local, preso se feriu no momento da prisão e precisa de atendimento médico.
Não sendo urgente, o contato inicial com a unidade prisional deve ater-se a informações sobre inclusão no rol de visitas, documentos necessários e forma de entrega.
Importante: Por questões de segurança não é informado por telefone nenhum tipo de movimentação de presos (saída para fórum, hospital), localização interna (cela e raio), e nem informações sigilosas e pessoais (matrícula prisional).', 'Posso ligar na unidade prisional para saber se meu familiar está bem?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (4, 'O que é rol de visitas?', 'O rol de visita é a relação de pessoas autorizadas a visitar a pessoa presa. São familiares de 2º grau (pai, mãe, filhos, irmãos, avós, esposa/companheira) com quem ele mantém vínculo familiar.', 'O que é rol de visitas?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (5, 'Como faço o cadastro no rol de visitas?', 'Ao adentrar na unidade prisional o preso será chamado para indicar de quais familiares ele quer receber visitas, ou seja, o familiar primeiro deve ser incluído pelo preso.
Após essa indicação o familiar poderá encaminhar a documentação necessária para confecção da carteirinha de visitante.', 'Como faço o cadastro no rol de visitas?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (6, 'Existe um período para que eu encaminhe essa documentação para unidade?', 'Sim. Ao adentrar em uma unidade prisional a pessoa presa ficará de 10 (dez) a 30 (trinta) dias em regime de inclusão e nesse período não recebe visitas.
O Regime de inclusão é necessário para verificar se a pessoa presa não terá problemas de convívio com os demais detentos da unidade prisional, em razão disso ele fica num setor separado da unidade prisional chamado de Inclusão.
Somente após o período de inclusão é que o familiar poderá encaminhar a documentação para confecção da carteirinha de visitante.', 'Existe um período para que eu encaminhe essa documentação para unidade?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (7, 'Quais os documentos necessários para me cadastrar no rol de visitas?', '• Cópia autenticada da carteira da identidade;
• Carteira Nacional de Habilitação (CNH);
• Carteira de Identidade de Estrangeiro ( RNE);
• Cópia do CPF; exceto se o número constar de outros documentos;
• Cópia do comprovante de residência com data não superior a 06(seis) meses contados da data da apresentação;
• Foto facial recente, em padrão 3×4;
• Comprovação da condição de cônjuge ou companheira (certidão de casamento, declaração de união estável);
• Certidão de antecedentes criminais.
Atenção: A unidade prisional poderá solicitar a apresentação dos documentos originais junto com as cópias mencionadas acima.', 'Quais os documentos necessários para me cadastrar no rol de visitas?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (8, 'Como faço para encaminhar a documentação para cadastro em rol?', 'A documentação poderá ser encaminhada via e-mail, correspondência ou entregue pessoalmente na unidade prisional, caberá a unidade prisional verificar a forma de recebimento.', 'Como faço para encaminhar a documentação para cadastro em rol?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (9, 'Existe um prazo para a unidade prisional autorizar minha visita?', 'Após o envio da documentação, o Diretor de Segurança e Disciplina da unidade prisional deverá decidir se autoriza ou não a visita.
O prazo para essa decisão é de 05 dias úteis que deverão ser contados a partir da entrega de toda a documentação exigida.
Atenção: se houver necessidade de complementação da documentação esse prazo poderá ser alterado.', 'Existe um prazo para a unidade prisional autorizar minha visita?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (10, 'A unidade prisional pode negar a autorização de visita para visitante?', 'Pode ocorrer negativa de autorização nos casos em que o visitante não encaminhou corretamente a documentação solicitada; não comprovou vínculo familiar com a pessoa presa; não comprovou a condição de companheira (o) da pessoa presa.', 'A unidade prisional pode negar a autorização de visita para visitante?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (11, 'Se o preso for transferido de unidade eu tenho que fazer a carteirinha novamente?', 'Em caso de transferência do preso o Diretor de Segurança e Disciplina da unidade, para qual ele foi transferido, deverá avaliar a necessidade complementação da documentação, não sendo cabível pode autorizar o ingresso da visitante com a mesma carteirinha.', 'Se o preso for transferido de unidade eu tenho que fazer a carteirinha novamente?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (12, 'Preciso ter a carteirinha de visitante para mandar o “jumbo”?', 'Sim. Apenas visitantes autorizadas podem manter contato com a pessoa presa e encaminhar itens de higiene, alimentação e limpeza pelo Sedex.
Lembramos que o auxílio familiar é importante, contudo é suplementar ao principal fornecido pelo Estado, desse modo a pessoa presa ainda que não receba visitas e nem o “jumbo” permanece assistida pela unidade prisional, sendo fornecida alimentação diária, vestuário, material de limpeza e higiene pessoal.', 'Preciso ter a carteirinha de visitante para mandar o “jumbo”?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (13, 'Qual é a validade da carteirinha de visitante?', 'A Carteira de Visitante no sistema prisional do Estado de São Paulo tem validade de até 1 (um) ano a partir da data de emissão. Durante esse período, alguns documentos exigidos deverão ser atualizados, como o comprovante de residência, a Certidão de Antecedentes Criminais e a Certidão de Objeto e Pé.
Após o vencimento, é necessário realizar a renovação da carteira, apresentando a documentação atualizada exigida. Recomenda-se iniciar o processo de renovação com, no mínimo, 30 dias de antecedência, a fim de evitar a suspensão temporária das visitas.', 'Qual é a validade da carteirinha de visitante?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (14, 'A esposa/companheira da pessoa presa quando for adolescente “menor de idade” pode realizar visitas?', 'Se a visitante comprovar documentalmente que é casada com a pessoa presa não haverá impedimento para sua visita.
Caso a visitante mantenha união estável com a pessoa presa à unidade irá avaliar a visita e poderá solicitar autorização complementar dos responsáveis e ainda autorização judicial.', 'A esposa/companheira da pessoa presa quando for adolescente “menor de idade” pode realizar visitas?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (15, 'Não tenho vínculo familiar com a pessoa presa (sou amigo), porém gostaria de visitá-lo. Como faço?', 'Caso a pessoa presa não tenha nenhum familiar em seu rol de visitas (nenhum familiar visitando), a unidade prisional poderá avaliar e autorizar o ingresso de pessoa sem vínculo familiar em rol de visitas.', 'Não tenho vínculo familiar com a pessoa presa (sou amigo), porém gostaria de visitá-lo. Como faço?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (16, 'Sou tio(a) da pessoa presa, logo tenho vínculo familiar, posso visitar?', 'O vínculo familiar que autoriza visita à pessoa presa limita-se a parentesco de 2º grau (pai, mãe, avô, avó, filhos, irmãos).
Logo tios, primos, cunhados, sogros, não estão autorizados, salvo no caso da pessoa presa não ter nenhum familiar no rol de visitas.', 'Sou tio(a) da pessoa presa, logo tenho vínculo familiar, posso visitar?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (17, 'Sou pai/mãe adotiva da pessoa presa, posso visitar?', 'Se a adoção tiver ocorrido legalmente (decisão judicial) não há impedimento. Todavia, se a situação não for documentada “pai e/ou mãe de criação” o pedido para visita deverá ser acompanhada de autorização judicial.
Se a situação envolver padrasto/madrasta também deverá ter autorização judicial.', 'Sou pai/mãe adotiva da pessoa presa, posso visitar?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (18, 'Como registrar filhos de pessoas privadas de liberdade?', 'O registro de filhos de pessoas privadas de liberdade pode ser realizado de duas formas:
Quando o pai não reconhece a paternidade: o registro deve ser feito por meio de processo judicial.
Quando o pai reconhece a paternidade: o registro pode ocorrer mediante declaração voluntária da pessoa privada de liberdade. É importante que a mãe da criança envie a certidão de nascido vivo ao serviço social da unidade, para que sejam realizados os trâmites legais.
Nos casos de nascimento ocorrido durante o cumprimento de pena, a equipe da unidade prisional deve providenciar o registro civil em articulação com a Defensoria Pública ou com cartório conveniado.
Importante: em casos de reconhecimento de paternidade, a unidade pode auxiliar o custodiado a formalizar o processo junto ao cartório, com apoio do setor de reintegração social da unidade prisional.', 'Como registrar filhos de pessoas privadas de liberdade?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (19, 'É possível que um mesmo familiar esteja em mais de um rol de visitas?', 'Sim. É permitido que um familiar esteja no rol de visitas de mais de um custodiado, desde que o grau de parentesco ou vínculo afetivo seja comprovado. O visitante deverá apresentar documentação comprobatória (como certidão de nascimento, casamento ou declaração de união estável) para cada vínculo informado.
Cada unidade prisional analisará o pedido conforme suas condições de segurança, capacidade de atendimento e critérios administrativos.
Atenção: a inclusão simultânea em mais de um rol poderá estar sujeita a limitações logísticas da unidade (dias e horários distintos), conforme o planejamento interno de visitas.', 'É possível que um mesmo familiar esteja em mais de um rol de visitas?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (20, 'Há alguma proibição de entrada de crianças/adolescentes nas unidades prisionais do Estado?', 'A entrada de crianças e adolescentes, para visitas comuns, é permitida somente quando a criança ou adolescente for filho ou neto do preso a ser visitado. As crianças e adolescentes devem estar acompanhadas por seu responsável legal ou de fato, independentemente de autorização judicial.', 'Há alguma proibição de entrada de crianças/adolescentes nas unidades prisionais do Estado?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (21, 'Como faço para retirar o meu nome do rol de visitas de uma pessoa presa.', 'Se a visitante não possui mais vínculo marital (esposa) ou afetiva (companheira) com a pessoa preso pode solicitar, por escrito, a retirada de seu nome junto a unidade prisional em que o preso está.
Modelo de Pedido de Regularização de Rol', 'Como faço para retirar o meu nome do rol de visitas de uma pessoa presa.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (22, 'E se a pessoa já estiver em liberdade, como faço para pedir a exclusão do meu nome do rol de visitas.', 'Se a visitante não tem mais vínculo com o preso e não tem pedido para visitar outro preso na condição de companheiro/esposa, a documentação deve ser encaminhada para última unidade em que ex-marido/ex-companheiro estava cumprindo pena.
Se a visitante não possui mais vínculo com o preso, porém possui novo relacionamento com outra pessoa que está presa, a documentação deverá ser para a unidade prisional em que seu atual marido/companheiro esteja.', 'E se a pessoa já estiver em liberdade, como faço para pedir a exclusão do meu nome do rol de visitas.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (23, 'Fiz a regularização de rol e agora a unidade me disse que devo aguardar 180 dias para pode visitar meu atual companheiro.', 'Conforme determinado pela Resolução 144/2010 da SAP a substituição de cônjuge ou companheiro durante o cumprimento de pena somente é possível nos casos de divórcio ou separação de fato, devendo ainda ser observado o prazo de 180 (cento e oitenta) dias para inclusão de novo companheiro ou cônjuge.', 'Fiz a regularização de rol e agora a unidade me disse que devo aguardar 180 dias para pode visitar meu atual companheiro.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (24, 'Por quanto tempo meu nome fica no sistema de visitante da SAP?', 'Enquanto a visitante declarar a existência de vínculo marital/união estável o nome dela estará relacionado a pessoa presa.
O nome da visitante será inativado quando: 1) o preso sair em liberdade; 2) quando ela ficar por mais de 01 ano sem realizar visitas, sem encaminhar Sedex “jumbo”, ou mesmo sem trocar correspondência com a pessoa presa.
Importante: Essas regras de inativação de rol, mencionadas acima, somente são válidas para situações ocorridas depois da publicação da Resolução SAP 160/2022, ou seja, 07/02/2023.', 'Por quanto tempo meu nome fica no sistema de visitante da SAP?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (25, 'A unidade prisional pode suspender visitantes?', 'Os visitantes são considerados usuários do serviço público nos termos da lei estadual 10.294/1999, e para além dos direitos previstos na lei também têm deveres que devem ser observados junto às unidades prisionais. O visitante que deixar de observar seus deveres poderá sofrer suspensão administrativa e ficar impedida de realizar visitas pelo período determinado pela administração.', 'A unidade prisional pode suspender visitantes?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (26, 'A Ouvidoria pode solicitar a retirada da minha suspensão.', 'As situações que envolvem suspensões administrativas são de competência exclusiva dos Diretores das Unidades Prisionais e, portanto, a Ouvidoria não pode intervir na suspensão em si, atuando apenas na verificação das garantias do contraditório e da ampla defesa, ou seja, se a visitante foi ouvida na unidade, se pode produzir provas a seu favor, etc...
A visitante pode fazer pedido de reconsideração junto à unidade prisional (pedido escrito dirigido ao Diretor Geral da unidade), ou se for o caso solicitar revisão judicial.', 'A Ouvidoria pode solicitar a retirada da minha suspensão.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (27, 'O que eu posso encaminhar para a pessoa presa via Sedex?', 'Pode ser encaminhado via SEDEX alimentos não perecíveis, vestuário, calçados, material de higiene pessoal e limpeza.
Atualmente podem ser encaminhadas em CAIXAS de qualquer numeração (nº 01/05) e devem obrigatoriamente pesar até 12 kg.', 'O que eu posso encaminhar para a pessoa presa via Sedex?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (28, 'Posso enviar dinheiro para a pessoa presa?', 'Não é permitida a entrada de dinheiro nas unidades prisionais do Estado.
O familiar que deseja auxiliar a pessoa presa pode encaminhar valores através do VALE POSTAL, que é um serviço disponível nas agências dos Correios.
A visitante também poderá encaminhar valores via PIX, da unidade prisional.
Para isso é necessário estar devidamente autorizado como visitante do preso e contatar a unidade prisional para informações sobre conta para depósito dos valores.', 'Posso enviar dinheiro para a pessoa presa?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (29, 'Como faço para solicitar a transferência do meu familiar preso?', 'Os pedidos de transferências devem ser feitos por escrito e endereçados as Coordenadorias Regionais de Unidades Prisionais ou entregue na unidade prisional em que o preso se encontra. Podem ser feitas pelo familiar, advogado e a própria pessoa presa.
Modelo de Pedido de Aproximação Familiar', 'Como faço para solicitar a transferência do meu familiar preso?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (30, 'Quais os requisitos da transferência por aproximação familiar.', 'Cumprimento de 1/6 da pena, não ter falta disciplinar recente, não possuir envolvimento em organização criminosa, estar a doze meses em unidade prisional da SAP.
O pedido deve ser instruído com comprovante de residência dos familiares do preso (aqueles que estão no rol) na região da unidade prisional pretendida.', 'Quais os requisitos da transferência por aproximação familiar.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (31, 'Como faço para que meu familiar seja transferido para uma Penitenciária.', 'As Penitenciárias destinam-se ao cumprimento de pena do regime fechado, assim é necessário que a pessoa presa tenha condenação definitiva em regime fechado. Não há necessidade de pedido, já que as unidades prisionais encaminham a relação de presos condenados para as Coordenadorias Regionais efetuarem as transferências.', 'Como faço para que meu familiar seja transferido para uma Penitenciária.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (32, 'Como faço para meu familiar ser transferido para unidade de regime semiaberto.', 'A transferência para unidades prisionais do regime semiaberto decorre de decisão judicial que concede a progressão de regime. Assim, não há necessidade de pedido, já que a unidade prisional será intimada para realizar a transferência em conjunto com a Coordenadoria Regional.', 'Como faço para meu familiar ser transferido para unidade de regime semiaberto.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (33, 'Quais os requisitos para solicitar transferência para um “CR” Centro de Ressocialização.', 'A pessoa presa não pode ter condenação superior a 10 anos, deve ser primário e não estar respondendo a outro processo; não pode apresentar indícios de participação em organização criminosa, quadrilha, facção; não pode ter falta disciplinar; e deve residir, comprovadamente, a uma distância não superior de 200 quilômetros da unidade prisional, por fim o preso deve passar por triagem e entrevista junto a equipe multidisciplinar do CRs.
O pedido deve ser encaminhado ao CR que a pessoa deseja ser transferida.', 'Quais os requisitos para solicitar transferência para um “CR” Centro de Ressocialização.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (34, 'Como faço para pedir transferência da pessoa presa para outro Estado?', 'A transferência interestadual deve ser autorizada pelo Juiz da Vara de Execuções Criminais do local em que a pessoa está presa, por isso o solicitante deverá ser representado por advogado ou pela Defensoria.
Autorizado judicialmente o pedido segue para o juiz da execução do local em que fica a unidade desejada para a transferência.
Havendo concordância o pedido segue para manifestação das Secretarias Estaduais de Administração Penitenciária.
Havendo concordância de todos necessário aguardar para definição de escolta e custos.', 'Como faço para pedir transferência da pessoa presa para outro Estado?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (35, 'Como faço para o pedir atendimento jurídico para a pessoa presa?', 'A assistência jurídica ao preso compete a Defensoria Pública do Estado. Dentro das unidades prisionais do Estado o atendimento é feito pelo advogado da Funap e pode ser solicitado pelo próprio preso.
Pedidos judiciais só podem ser feitos através de advogados ou Defensor Público. Por isso, é importante que o familiar que busca atendimento jurídico para a pessoa presa procure a Defensoria Pública do Estado caso não tenha condições de contratar um advogado particular.
Para saber mais acesse: www.defensoria.sp.def.br.', 'Como faço para o pedir atendimento jurídico para a pessoa presa?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (36, 'Como faço regularizar minha situação de evadido junto a SAP?', 'Deve ser feito o procedimento chamado de “baixa na captura”, mas atenção é necessária decisão judicial determinando a extinção da punibilidade.
Os pedidos devem ser encaminhados para as CAEFs instruídos com a cópia da decisão judicial.
Confira os endereços e contatos das CAEFs no site: https://www1.sap.sp.gov.br/sp/unidades-prisionais/crsc.html#caefs', 'Como faço regularizar minha situação de evadido junto a SAP?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (37, 'O que é o Boletim Informativo “BI” juntado no processo de execução do preso?', 'O BI (boletim informativo) é o documento necessário para instruir os pedidos de progressão de regime, livramento condicional, indulto, etc... É nesse documento que virá às informações sobre o cumprimento de pena pela pessoa presa (unidades prisionais em que cumpriu pena, trabalho, estudo, se possui falta disciplinar, tempo de pena) e permitirá ao juiz avaliar se o preso tem condições de progredir para regime intermediário.', 'O que é o Boletim Informativo “BI” juntado no processo de execução do preso?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (38, 'Como faço para pedir o Boletim Informativo “BI”?', 'O “BI” só pode ser pedido por advogado constituído ou pela Defensoria Pública e deve ser feito junto à unidade prisional em que o preso está. O pedido deve ser por escrito e protocolado na unidade que terá um prazo de 20dias úteis para confeccioná-lo e entregá-lo ao solicitante.', 'Como faço para pedir o Boletim Informativo “BI”?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (39, 'Como faço para saber sobre o exame criminológico?', 'O exame criminológico pode ser solicitado como requisito para progressão de regime ou livramento condicional, normalmente é solicitado pelo Ministério Público, porém o Juiz pode pedir também. A SAP tem a função de designar técnicos (assistentes sociais, psicólogas ou psiquiatras) para a realização desse exame, quem irá avaliar o teor do laudo é o Poder Judiciário.', 'Como faço para saber sobre o exame criminológico?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (40, 'Como faço para pedir o atestado de permanência carcerária?', 'A Certidão de Permanência Carcerária é documento comprobatório da prisão da pessoa presa e necessário para instruir o pedido de auxilio reclusão.
Conforme os termos de Cooperação Técnica firmado entre o INSS e a SAP a solicitação deve ser feita:
• pelo próprio INSS (aqui a pessoa vai até a agência do INSS e pede para eles solicitarem o documento para a SAP através do sistema GEPEN);
• pela visitante ou pelo advogado diretamente na unidade prisional em que o preso está;
• havendo dificuldades nos procedimentos acima orientamos que entre em contato com uma das unidades da CAEF (Centro de atendimento ao egresso e família) através dos endereços constantes no site da SAP https://www1.sap.sp.gov.br/sp/unidades-prisionais/crsc.html#caefs através dos endereços constantes no site da SAP www.sap.sp.gov.br/sec_adm_penitenciaria.', 'Como faço para pedir o atestado de permanência carcerária?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (41, 'O que são as CAEFs e quais serviços podem ser solicitadas a ela.', 'As Centrais de Atenção ao egresso e Família é o setor subordinado a Coordenadoria da Reintegração Social que responde pela assistência direta ao egresso do sistema penitenciário e também aos seus familiares.
Através das CAEFs, o preso e seus familiares, podem solicitar documentações (2º via de RG, CPF, título eleitoral), oportunidades em cursos e vagas para empregos, orientação quanto ao funcionamento e acesso do Projeto Conexão Familiar (visitas virtuais e e-mails).
Para saber mais sobre os serviços que podem ser solicitados via CAEF acesse o site da SAP https://www1.sap.sp.gov.br/sp/unidades-prisionais/crsc.html#caefs.', 'O que são as CAEFs e quais serviços podem ser solicitadas a ela.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (42, 'Como faço para enviar um e-mail para o meu familiar preso?', 'Para enviar e-mails para a pessoa presa é necessário estar incluída no rol de visitas. O envio é feito através do formulário disposto no site da SAP e pode ser feito 01 (um) envio por mês.', 'Como faço para enviar um e-mail para o meu familiar preso?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (43, 'Qual prazo para retorno das mensagens?', 'As mensagens encaminhadas aos reeducandos(as) serão impressas e entregues ao destinatário. O/A visitante receberá por e-mail a confirmação do recebimento pelo reeducando. NÃO HAVERÁ OUTRA RESPOSTA, apenas a confirmação do recebimento da mensagem.', 'Qual prazo para retorno das mensagens?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (44, 'Estou com dificuldades para receber retorno das minhas mensagens.', 'O/A visitante receberá por e-mail a confirmação do recebimento pelo reeducando. NÃO HAVERÁ OUTRA RESPOSTA, apenas a confirmação do recebimento da mensagem.
Caso não tenha recebido retorno de sua mensagem no prazo mencionado é necessário verificar:
• se você é visitante autorizada a encaminhar mensagens.
• se a mensagem não foi encaminhada para direto na caixa de spam;
• se a mensagem respeitava os parâmetros estabelecidos pela Res. 94/2020 SAP; ou seja, se estava dentro dos limites de caracteres, se não continha conteúdo impróprio, e se foi respeitado o limite semanal de uma mensagem.', 'Estou com dificuldades para receber retorno das minhas mensagens.', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (45, 'A unidade pode “censurar” meu e-mail e não encaminhar para o preso?', 'Caso seja identificada nas mensagens encaminhadas via e-mail, palavras ofensivas, ameaçadoras, linguagens pejorativas ou de baixo calão e ainda mensagens cifradas ou em códigos a unidade prisional pode barrar o envio do e-mail, além de analisar necessidade de suspensão do remetente.', 'A unidade pode “censurar” meu e-mail e não encaminhar para o preso?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (46, 'O que é Prisão Civil?', 'A prisão civil é quando alguém vai preso por não cumprir obrigações legais, como pagar pensão alimentícia ou dívidas determinadas pelo tribunal. Geralmente, a prisão civil é aplicada como último recurso, após esgotadas outras medidas para garantir o cumprimento das obrigações civis.', 'O que é Prisão Civil?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (47, 'Quem está sujeito à Prisão Civil?', 'A prisão civil é quando alguém vai preso por não cumprir obrigações legais, como pagar pensão alimentícia ou dívidas determinadas pelo tribunal. Geralmente, a prisão civil é aplicada como último recurso, após esgotadas outras medidas para garantir o cumprimento das obrigações civis.', 'Quem está sujeito à Prisão Civil?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (48, 'Os presos de Prisão Civil ficam no mesmo ambiente que os presos que estão em cumprimento de pena?', 'Não.
As pessoas que estão presas por não pagar pensão alimentícia ficam em áreas separadas dentro de prisões comuns. Essas áreas são destinadas especificamente para aqueles que estão cumprindo pena por causa da pensão alimentícia.', 'Os presos de Prisão Civil ficam no mesmo ambiente que os presos que estão em cumprimento de pena?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (49, 'E as regras para visitação? são diferentes?', 'As regras para visitar pessoas em prisões, incluindo aquelas que abrigam presos por pensão alimentícia, seguem as normas da Secretaria de Administração Penitenciária. Isso inclui se cadastrar antes, envio de documentos de identificação, seguir regras sobre o que pode ou não levar durante a visita, passar por revista e seguir horários específicos para as visitas.
É importante ressaltar que as regras para visitação podem sofrer alterações e é fundamental consultar diretamente a unidade prisional ou o site da Secretaria de Administração Penitenciária local para obter as informações atualizadas e detalhadas sobre os procedimentos e requisitos para visitar um preso.', 'E as regras para visitação? são diferentes?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (50, 'Como fazer para localizar meu familiar que foi preso civilmente?', 'A SAP possui unidades especificas para esse perfil de presos. É possível verificar diretamente no Mapa de Unidades Prisionais - nas que possuem a sigla PC há vagas para Prisão Civil: https://www1.sap.sp.gov.br/sp/unidades-prisionais/complexos-penais.html
É possível verificar se a pessoa está custodiada na SAP e onde está pelo sistema de Paradeiro de Custodiados: https://portal.sap.sp.gov.br/formularios/paradeiro', 'Como fazer para localizar meu familiar que foi preso civilmente?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'),
        (51, 'Consigo falar nas Unidades Prisionais via WhatsApp?', 'Informamos que o atendimento automatizado via WhatsApp está disponível conforme os contatos divulgados na página de contatos e endereços, facilitando o acesso a informações e serviços.
Por meio desse canal, é possível tirar dúvidas sobre horários de visita, cadastro no rol, envio de documentos e itens, entre outros assuntos relacionados ao sistema prisional.
O botão de acesso ao WhatsApp de cada unidade está disponível na página oficial da SAP, identificado com o ícone do aplicativo. Basta clicar no símbolo correspondente à unidade desejada para iniciar a conversa diretamente.', 'Consigo falar nas Unidades Prisionais via WhatsApp?', 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html')
),
target_bots AS (
    SELECT id AS app_bot_id
      FROM app_bot
     WHERE ativo = 'Y'
),
base_orders AS (
    SELECT tb.app_bot_id, COALESCE(MAX(f.ordem), 0) AS max_ordem
      FROM target_bots tb
      LEFT JOIN app_bot_faq f ON f.app_bot_id = tb.app_bot_id
     GROUP BY tb.app_bot_id
),
purge AS (
    DELETE FROM app_bot_faq f
     USING target_bots tb
     WHERE f.app_bot_id = tb.app_bot_id
       AND f.fonte_externa = 'https://www1.sap.sp.gov.br/ouvidoria/ouvidoria-faq.html'
    RETURNING f.id
)
INSERT INTO app_bot_faq (
    app_bot_id, pergunta, resposta, palavras_chave, fonte_externa, embedding_text, ordem, ativo, criado_em, atualizado_em
)
SELECT bo.app_bot_id,
       sf.pergunta,
       sf.resposta,
       sf.palavras_chave,
       sf.fonte_externa,
       sf.pergunta || E'\n\n' || sf.resposta AS embedding_text,
       bo.max_ordem + sf.ordem AS ordem,
       'Y' AS ativo,
       NOW(),
       NOW()
  FROM source_faq sf
 CROSS JOIN base_orders bo
 ORDER BY bo.app_bot_id, sf.ordem;
